// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pgeuQ3TOgysbVUzHfQyiJi9qEsqPm0o',
    appId: '1:397010925516:android:d0e78d21d52e58ecde8f69',
    messagingSenderId: '397010925516',
    projectId: 'smart-eyes-f3ae5',
    storageBucket: 'smart-eyes-f3ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7xZP6LUSmzfCUYugmgzxA445MBXqH9IU',
    appId: '1:397010925516:ios:2c5f1c4527acdd86de8f69',
    messagingSenderId: '397010925516',
    projectId: 'smart-eyes-f3ae5',
    storageBucket: 'smart-eyes-f3ae5.appspot.com',
    iosBundleId: 'com.oab.smart.eyes.smarteyes',
  );
}
